package com.civicconnect.backend.repository;

import com.civicconnect.backend.model.Ngo;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface NgoRepository extends JpaRepository<Ngo, Long> {
    // Basic CRUD is auto-generated by JpaRepository
}